# Perceptron

In [1]:
import numpy as np

X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([0,1,1,1])

# weights initialization
w1 = 0.1
w2 = 0.2
w_bias = 1

threshold = 0.1

epochs = 10

for epoch in range(epochs):
    print(f"\nEpoch {epoch+1}")
    
    for i in range(len(X)):
        x1 = X[i][0]
        x2 = X[i][1]
        bias = 1

        # net calculation
        net = x1*w1 + x2*w2 + bias*w_bias

        # activation
        y_pred = 1 if net >= threshold else 0

        t = y[i]

        # update rules exactly as you wrote
        if y_pred != t:
            
            # case 1: y = 0, want y = 1 (increase weights)
            if y_pred == 0 and t == 1:
                w1 = w1 + x1
                w2 = w2 + x2
                w_bias = w_bias + bias

            # case 2: y = 1, want y = 0 (decrease weights)
            elif y_pred == 1 and t == 0:
                w1 = w1 - x1
                w2 = w2 - x2   
                w_bias = w_bias - bias

        print(f"x1={x1}, x2={x2}, target={t}, pred={y_pred}, w1={w1}, w2={w2}, wb={w_bias}")


Epoch 1
x1=0, x2=0, target=0, pred=1, w1=0.1, w2=0.2, wb=0
x1=0, x2=1, target=1, pred=1, w1=0.1, w2=0.2, wb=0
x1=1, x2=0, target=1, pred=1, w1=0.1, w2=0.2, wb=0
x1=1, x2=1, target=1, pred=1, w1=0.1, w2=0.2, wb=0

Epoch 2
x1=0, x2=0, target=0, pred=0, w1=0.1, w2=0.2, wb=0
x1=0, x2=1, target=1, pred=1, w1=0.1, w2=0.2, wb=0
x1=1, x2=0, target=1, pred=1, w1=0.1, w2=0.2, wb=0
x1=1, x2=1, target=1, pred=1, w1=0.1, w2=0.2, wb=0

Epoch 3
x1=0, x2=0, target=0, pred=0, w1=0.1, w2=0.2, wb=0
x1=0, x2=1, target=1, pred=1, w1=0.1, w2=0.2, wb=0
x1=1, x2=0, target=1, pred=1, w1=0.1, w2=0.2, wb=0
x1=1, x2=1, target=1, pred=1, w1=0.1, w2=0.2, wb=0

Epoch 4
x1=0, x2=0, target=0, pred=0, w1=0.1, w2=0.2, wb=0
x1=0, x2=1, target=1, pred=1, w1=0.1, w2=0.2, wb=0
x1=1, x2=0, target=1, pred=1, w1=0.1, w2=0.2, wb=0
x1=1, x2=1, target=1, pred=1, w1=0.1, w2=0.2, wb=0

Epoch 5
x1=0, x2=0, target=0, pred=0, w1=0.1, w2=0.2, wb=0
x1=0, x2=1, target=1, pred=1, w1=0.1, w2=0.2, wb=0
x1=1, x2=0, target=1, pred=1, w1=0.1,

# SLP with Single output

In [ ]:
import numpy as np

X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([0,1,1,1])

# initialize weights
w1 = 0.1
w2 = 0.2
wb = -0.2

learning_rate = 0.1
threshold = 0.1
epochs = 10

for epoch in range(epochs):
    print(f"\nEpoch {epoch+1}")
    
    for i in range(len(X)):
        x1 = X[i][0]
        x2 = X[i][1]
        bias = 1

        # net input
        net = x1*w1 + x2*w2 + bias*wb

        # activation
        y_pred = 1 if net >= threshold else 0

        t = y[i]

        # error
        error = t - y_pred

        # SLP update rule 
        w1 = w1 + learning_rate * x1 * error
        w2 = w2 + learning_rate * x2 * error
        wb = wb + learning_rate * bias * error

        print(f"x1={x1}, x2={x2}, t={t}, y={y_pred}, w1={w1}, w2={w2}, wb={wb}")


Epoch 1
x1=0, x2=0, t=0, y=0, w1=0.1, w2=0.2, wb=-0.2
x1=0, x2=1, t=1, y=0, w1=0.1, w2=0.30000000000000004, wb=-0.1
x1=1, x2=0, t=1, y=0, w1=0.2, w2=0.30000000000000004, wb=0.0
x1=1, x2=1, t=1, y=1, w1=0.2, w2=0.30000000000000004, wb=0.0

Epoch 2
x1=0, x2=0, t=0, y=0, w1=0.2, w2=0.30000000000000004, wb=0.0
x1=0, x2=1, t=1, y=1, w1=0.2, w2=0.30000000000000004, wb=0.0
x1=1, x2=0, t=1, y=1, w1=0.2, w2=0.30000000000000004, wb=0.0
x1=1, x2=1, t=1, y=1, w1=0.2, w2=0.30000000000000004, wb=0.0

Epoch 3
x1=0, x2=0, t=0, y=0, w1=0.2, w2=0.30000000000000004, wb=0.0
x1=0, x2=1, t=1, y=1, w1=0.2, w2=0.30000000000000004, wb=0.0
x1=1, x2=0, t=1, y=1, w1=0.2, w2=0.30000000000000004, wb=0.0
x1=1, x2=1, t=1, y=1, w1=0.2, w2=0.30000000000000004, wb=0.0

Epoch 4
x1=0, x2=0, t=0, y=0, w1=0.2, w2=0.30000000000000004, wb=0.0
x1=0, x2=1, t=1, y=1, w1=0.2, w2=0.30000000000000004, wb=0.0
x1=1, x2=0, t=1, y=1, w1=0.2, w2=0.30000000000000004, wb=0.0
x1=1, x2=1, t=1, y=1, w1=0.2, w2=0.30000000000000004, wb=0.0

E

# SLP with multiple outputs

In [29]:
import numpy as np

X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([[0,0],
              [1,0],
              [1,0],
              [1,1]])

learning_rate = 0.1

# weights (as given)
w11, w21, wb1 = 0.2, 0.3, 0.0
w12, w22, wb2 = 0.1, 0.2, 0.7

threshold1 = 0.1
threshold2 = 1

epochs = 10

for epoch in range(epochs):
    print(f"\nEpoch {epoch+1}")

    for i in range(len(X)):
        x1, x2 = X[i]
        bias = 1

        # ---------- OUTPUT 1 ----------
        net1 = x1*w11 + x2*w21 + bias*wb1
        y1 = 1 if net1 >= threshold1 else 0
        t1 = y[i][0]
        e1 = t1 - y1

        w11 = w11 + learning_rate * x1 * e1
        w21 = w21 + learning_rate * x2 * e1
        wb1 = wb1 + learning_rate * bias * e1

        # ---------- OUTPUT 2 ----------
        net2 = x1*w12 + x2*w22 + bias*wb2
        y2 = 1 if net2 >= threshold2 else 0
        t2 = y[i][1]
        e2 = t2 - y2

        w12 = w12 + learning_rate * x1 * e2
        w22 = w22 + learning_rate * x2 * e2
        wb2 = wb2 + learning_rate * bias * e2

        print(f"x=({x1},{x2}) | "
            f"actual=({t1},{t2}) | "
            f"pred=({y1},{y2}) | "
            f"w1=({w11:.2f},{w21:.2f},{wb1:.2f}) | "
            f"w2=({w12:.2f},{w22:.2f},{wb2:.2f})")


Epoch 1
x=(0,0) | actual=(0,0) | pred=(0,0) | w1=(0.20,0.30,0.00) | w2=(0.10,0.20,0.70)
x=(0,1) | actual=(1,0) | pred=(1,0) | w1=(0.20,0.30,0.00) | w2=(0.10,0.20,0.70)
x=(1,0) | actual=(1,0) | pred=(1,0) | w1=(0.20,0.30,0.00) | w2=(0.10,0.20,0.70)
x=(1,1) | actual=(1,1) | pred=(1,1) | w1=(0.20,0.30,0.00) | w2=(0.10,0.20,0.70)

Epoch 2
x=(0,0) | actual=(0,0) | pred=(0,0) | w1=(0.20,0.30,0.00) | w2=(0.10,0.20,0.70)
x=(0,1) | actual=(1,0) | pred=(1,0) | w1=(0.20,0.30,0.00) | w2=(0.10,0.20,0.70)
x=(1,0) | actual=(1,0) | pred=(1,0) | w1=(0.20,0.30,0.00) | w2=(0.10,0.20,0.70)
x=(1,1) | actual=(1,1) | pred=(1,1) | w1=(0.20,0.30,0.00) | w2=(0.10,0.20,0.70)

Epoch 3
x=(0,0) | actual=(0,0) | pred=(0,0) | w1=(0.20,0.30,0.00) | w2=(0.10,0.20,0.70)
x=(0,1) | actual=(1,0) | pred=(1,0) | w1=(0.20,0.30,0.00) | w2=(0.10,0.20,0.70)
x=(1,0) | actual=(1,0) | pred=(1,0) | w1=(0.20,0.30,0.00) | w2=(0.10,0.20,0.70)
x=(1,1) | actual=(1,1) | pred=(1,1) | w1=(0.20,0.30,0.00) | w2=(0.10,0.20,0.70)

Epoch 4
x=(0

# Perceptron Keras

In [30]:
import numpy as np
import tensorflow as tf

X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([0,1,1,1])

model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(2,), activation='sigmoid')
])

model.compile(loss='mse')

model.fit(X, y, epochs=10, verbose=1)


Epoch 1/10


c:\Users\MG magic\anaconda3\envs\dl_torch\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - loss: 0.2637
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.2627
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.2620
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.2614
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.2609
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.2604
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.2600
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.2596
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.2592
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.2588


In [31]:
print(model.predict(X))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
[[0.50430894]
 [0.28719884]
 [0.7500648 ]
 [0.5430665 ]]


In [32]:
print(model.predict(X).round())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[1.]
 [0.]
 [1.]
 [1.]]


# SLP (Delta Rule equivalent) Keras

In [33]:
import numpy as np
import tensorflow as tf

X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([0,1,1,1])

model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(2,), activation='sigmoid')
])

model.compile(loss='mse')

model.fit(X, y, epochs=10, verbose=1)



Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 286ms/step - loss: 0.2605
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.2596
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.2589
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.2584
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.2579
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.2575
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.2571
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.2567
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.2563
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.2560


In [34]:
print(model.predict(X))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
[[0.5043078 ]
 [0.78229773]
 [0.27006778]
 [0.56650275]]


In [35]:
print(model.predict(X).round())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[1.]
 [1.]
 [0.]
 [1.]]


# Multi-Output SLP Keras

In [36]:
import numpy as np
import tensorflow as tf

X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([[0,0],
              [1,0],
              [1,0],
              [1,1]])

model = tf.keras.Sequential([
    tf.keras.layers.Dense(2, input_shape=(2,), activation='sigmoid')
])

model.compile(loss='mse')

model.fit(X, y, epochs=10, verbose=1)



Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 280ms/step - loss: 0.2081
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.2076
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.2072
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.2069
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.2067
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.2064
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 0.2062
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.2060
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.2058
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.2056


In [37]:
print(model.predict(X))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[[0.5042455  0.495671  ]
 [0.7327734  0.74878705]
 [0.5716301  0.2961318 ]
 [0.7824944  0.56062126]]


In [38]:
print(model.predict(X).round())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[1. 0.]
 [1. 1.]
 [1. 0.]
 [1. 1.]]
